export default [
    {
      id: 0,
      description: 'Сделайте 3 шага вперед. Если проходите старт, получите 200$',
      step: 3,
      name: 'Шанс',
      img: 'chanceIcon',
      type: 'chance',
    },
    {
      id: 1,
      description: 'Сделайте 5 шагов вперед. Если проходите старт, получите 200$',
      step: 5,
      name: 'Шанс',
      img: 'chanceIcon',
      type: 'chance',
    },
    {
      id: 2,
      description: 'Сделайте 5 шагов назад',
      step: -5,
      name: 'Шанс',
      img: 'chanceIcon',
      type: 'chance',
    },
    {
      id: 3,
      description: 'Сделайте 10 шагов, Если проходите старт, получите 200$',
      step: 10,
      name: 'Шанс',
      img: 'chanceIcon',
      type: 'chance',
    },
    {
      id: 4,
      description: 'Сделайте шаг назад',
      step: -1,
      name: 'Шанс',
      img: 'chanceIcon',
      type: 'chance',
    },
]